"""Media Ops strategy helpers consumed by autopilot.

This module is intentionally small and dependency-light. It reads the strategy
weights generated by scripts/media_ops_agent.py and applies them to candidate
selection without requiring the scheduler to know the report internals.
"""
from __future__ import annotations

import json
import math
import re
from datetime import date, datetime
from pathlib import Path
from typing import Any

BASE_DIR = Path(__file__).resolve().parents[1]
WEIGHTS_FILE = BASE_DIR / "data" / "autopilot_strategy_weights.json"

STRATEGY_TOPICS = {
    "tech": {"ai_agent", "ai_model", "ai_tool", "semiconductor", "tech_leader", "creator_ai", "general"},
    "tech_judgement": {"ai_agent", "ai_model", "ai_tool", "semiconductor", "tech_leader", "creator_ai", "general"},
    "figure_tech": {"tech_leader", "semiconductor", "ai_model", "ai_agent"},
    "business_finance": {"ai_agent", "ai_model", "semiconductor", "tech_leader", "creator_ai", "general"},
    "entertainment": {"entertainment_kpop", "internet_culture", "general"},
    "entertainment_storyboard": {"entertainment_kpop", "internet_culture", "creator_ai", "general"},
}

MIN_CANDIDATE_SCORE = {
    "tech": 45.0,
    "tech_judgement": 45.0,
    "figure_tech": 42.0,
    "business_finance": 45.0,
    "entertainment": 55.0,
    "entertainment_storyboard": 50.0,
}

TOPIC_TERMS = {
    "ai_agent": ("AI agent", "agents", "automation", "operator", "Manus", "智能體", "代理"),
    "ai_model": ("GPT", "OpenAI", "Claude", "Gemini", "LLM", "AI model", "大模型", "模型"),
    "ai_tool": ("AI tools", "vibe coding", "prompt", "app", "developer tools", "工具"),
    "semiconductor": ("Nvidia", "Jensen Huang", "GPU", "TSMC", "chip", "半導體", "晶片", "輝達"),
    "tech_leader": ("Sam Altman", "Jensen Huang", "Elon Musk", "Satya Nadella", "Karpathy", "CEO"),
    "creator_ai": ("AI video editing", "YouTube Shorts", "Reels", "retention", "hook", "字幕", "封面"),
    "entertainment_kpop": ("Kpop", "MV", "ITZY", "aespa", "BLACKPINK", "BTS", "韓團"),
    "internet_culture": ("viral trend", "meme", "hot trend", "熱搜", "迷因"),
}

ENTITY_TERMS = {
    "nvidia": ("nvidia", "jensen", "黃仁勳", "輝達"),
    "tsmc": ("tsmc", "台積電", "張忠謀"),
    "openai": ("openai", "chatgpt", "gpt", "sam altman"),
    "google": ("google", "gemini", "pichai"),
    "microsoft": ("microsoft", "copilot", "satya"),
    "meta": ("meta", "zuckerberg", "llama"),
    "amd": ("amd", "lisa su", "蘇姿丰"),
    "apple": ("apple", "蘋果", "ios"),
    "tesla": ("tesla", "elon", "musk", "馬斯克"),
}

VIRAL_POSITIVE_TERMS = (
    "why",
    "how",
    "first",
    "finally",
    "secret",
    "leak",
    "leaked",
    "ban",
    "crisis",
    "warning",
    "mistake",
    "vs",
    "billion",
    "million",
    "surge",
    "collapse",
    "breakthrough",
    "reveals",
    "launches",
    "為什麼",
    "怎麼",
    "首次",
    "終於",
    "秘密",
    "流出",
    "禁令",
    "危機",
    "警告",
    "錯",
    "大漲",
    "暴跌",
    "突破",
    "揭露",
)

VIRAL_NEGATIVE_TERMS = (
    "announces update",
    "weekly roundup",
    "quarterly report",
    "press release",
    "minor update",
    "例行",
    "財報摘要",
    "小更新",
)

OFFBRAND_TERMS = (
    "binance",
    "crypto",
    "bitcoin",
    "幣安",
    "加密貨幣",
    "大纪元",
    "大紀元",
)


def load_weights(path: Path = WEIGHTS_FILE) -> dict[str, Any]:
    try:
        if path.exists():
            data = json.loads(path.read_text(encoding="utf-8"))
            return data if isinstance(data, dict) else {}
    except Exception:
        return {}
    return {}


def classify_candidate(item: dict[str, Any]) -> str:
    text = " ".join(str(item.get(k) or "") for k in ("title", "summary", "source", "channel")).lower()
    for topic, terms in TOPIC_TERMS.items():
        if any(term.lower() in text for term in terms):
            return topic
    if re.search(r"\bai\b|人工智慧|科技", text):
        return "ai_model"
    return "general"


def story_cluster(item: dict[str, Any]) -> str:
    text = " ".join(str(item.get(k) or "") for k in ("title", "summary", "source", "channel")).lower()
    topic = classify_candidate(item)
    for entity, terms in ENTITY_TERMS.items():
        if any(term.lower() in text for term in terms):
            return f"{topic}:{entity}"
    tokens = re.findall(r"[a-zA-Z0-9]{3,}|[\u4e00-\u9fff]{2,}", text)
    stop = {"news", "update", "official", "video", "2026", "2025", "新聞", "最新", "官方"}
    picked = [token.lower() for token in tokens if token.lower() not in stop][:3]
    if picked:
        return f"{topic}:{'-'.join(picked)}"
    return f"{topic}:general"


def source_key(item: dict[str, Any]) -> str:
    value = str(
        item.get("media_ops_source_key")
        or item.get("source")
        or item.get("channel")
        or item.get("source_name")
        or item.get("source_type")
        or "unknown"
    ).lower()
    value = re.sub(r"\s+", " ", value).strip()
    return value or "unknown"


def preferred_keyword(default_keyword: str, strategy: str, weights: dict[str, Any] | None = None) -> str:
    weights = weights or load_weights()
    topic_weights = weights.get("topic_weights") if isinstance(weights.get("topic_weights"), dict) else {}
    allowed = STRATEGY_TOPICS.get(strategy, STRATEGY_TOPICS["tech"])
    candidates = [(topic, float(topic_weights.get(topic) or 0)) for topic in allowed if topic in TOPIC_TERMS]
    if not candidates:
        return default_keyword
    topic, score = max(candidates, key=lambda x: x[1])
    if score <= 0:
        return default_keyword
    terms = TOPIC_TERMS.get(topic) or ()
    return terms[0] if terms else default_keyword


def candidate_keywords(default_keyword: str, strategy: str, weights: dict[str, Any] | None = None, limit: int = 3) -> list[str]:
    """Return multiple search seeds so a lane can escape one crowded topic."""
    weights = weights or load_weights()
    allowed = STRATEGY_TOPICS.get(strategy, STRATEGY_TOPICS["tech"])
    topic_weights = weights.get("topic_weights") if isinstance(weights.get("topic_weights"), dict) else {}
    focus = ((weights.get("direction") or {}).get("lane_focus_topics") or {}).get(strategy) or []

    fallback_by_strategy = {
        "tech": ["ai_tool", "ai_agent", "ai_model", "semiconductor"],
        "tech_judgement": ["ai_tool", "ai_agent", "ai_model", "semiconductor"],
        "figure_tech": ["tech_leader", "semiconductor", "ai_model"],
        "business_finance": ["ai_model", "semiconductor", "tech_leader", "creator_ai"],
        "entertainment": ["internet_culture", "entertainment_kpop"],
    }
    ordered_topics = []
    for topic in [*focus, *fallback_by_strategy.get(strategy, []), *allowed]:
        if topic in allowed and topic in TOPIC_TERMS and topic not in ordered_topics:
            ordered_topics.append(topic)

    scored = []
    fallback_topics = set(fallback_by_strategy.get(strategy, []))
    for idx, topic in enumerate(ordered_topics):
        raw_weight = topic_weights.get(topic)
        score = float(raw_weight) if raw_weight is not None else (0.75 if topic in fallback_topics else 0.45)
        if topic in focus:
            score += 0.25
        score -= idx * 0.01
        scored.append((score, topic))
    scored.sort(reverse=True)

    out: list[str] = []
    for _score, topic in scored:
        term = (TOPIC_TERMS.get(topic) or ("",))[0]
        if term and term.lower() not in {x.lower() for x in out}:
            out.append(term)
        if len(out) >= limit:
            break
    if default_keyword and default_keyword.lower() not in {x.lower() for x in out} and len(out) < limit:
        out.append(default_keyword)
    return out or [default_keyword or "AI"]


def lane_action(strategy: str, weights: dict[str, Any] | None = None) -> dict[str, Any]:
    weights = weights or load_weights()
    actions = weights.get("lane_actions") if isinstance(weights.get("lane_actions"), dict) else {}
    action = actions.get((strategy or "").lower()) if isinstance(actions, dict) else None
    if isinstance(action, dict):
        return action
    return {
        "action": "keep",
        "cadence_days": 1,
        "daily_quota": 1,
        "reason": "no lane action available",
    }


def daily_quota(strategy: str, weights: dict[str, Any] | None = None) -> int:
    action = lane_action(strategy, weights)
    try:
        return max(0, min(3, int(action.get("daily_quota") or 1)))
    except (TypeError, ValueError):
        return 1


def platform_action(strategy: str, platform: str, weights: dict[str, Any] | None = None) -> dict[str, Any]:
    weights = weights or load_weights()
    actions = weights.get("platform_actions") if isinstance(weights.get("platform_actions"), dict) else {}
    lane_actions = actions.get((strategy or "").lower()) if isinstance(actions, dict) else {}
    action = lane_actions.get((platform or "").lower()) if isinstance(lane_actions, dict) else None
    if isinstance(action, dict):
        return action
    return {"action": "keep", "reason": "no platform action available"}


def filter_platforms(strategy: str, platforms: list[str], weights: dict[str, Any] | None = None) -> list[str]:
    weights = weights or load_weights()
    kept: list[str] = []
    for platform in platforms:
        action = str(platform_action(strategy, platform, weights).get("action") or "keep").lower()
        if action == "pause":
            continue
        kept.append(platform)
    return kept


def should_run_lane(strategy: str, weights: dict[str, Any] | None = None, *, today: str | date | None = None) -> tuple[bool, str]:
    """Return whether autopilot should create this lane today.

    This is intentionally deterministic so the UI/manual run and cron make the
    same call from the latest Media Ops output.
    """
    action = lane_action(strategy, weights)
    action_name = str(action.get("action") or "keep").lower()
    reason = str(action.get("reason") or "")
    if action_name == "pause":
        return False, reason or "lane paused by Media Ops"

    cadence = _as_int(action.get("cadence_days") or 1)
    if action_name == "experiment" and cadence > 1:
        day = _date_ordinal(today)
        if day % cadence != 0:
            return False, reason or f"experiment cadence: every {cadence} days"
    return True, reason or f"lane action={action_name}"


def virality_score(item: dict[str, Any]) -> float:
    """Score stop-the-scroll potential independent of topic fit."""
    text = " ".join(str(item.get(k) or "") for k in ("title", "summary", "source", "channel")).lower()
    score = 0.0
    score += min(18.0, len(re.findall(r"\d+", text)) * 4.0)
    score += min(26.0, sum(1 for term in VIRAL_POSITIVE_TERMS if term.lower() in text) * 4.0)
    score -= min(18.0, sum(1 for term in VIRAL_NEGATIVE_TERMS if term.lower() in text) * 6.0)
    if "?" in text or "？" in text:
        score += 5.0
    if len(text) < 28:
        score -= 4.0
    if 42 <= len(text) <= 150:
        score += 3.0
    return round(max(-20.0, min(40.0, score)), 3)


def candidate_score(item: dict[str, Any], strategy: str, weights: dict[str, Any] | None = None) -> float:
    weights = weights or load_weights()
    topic = classify_candidate(item)
    topic_weights = weights.get("topic_weights") if isinstance(weights.get("topic_weights"), dict) else {}
    cluster_weights = weights.get("cluster_weights") if isinstance(weights.get("cluster_weights"), dict) else {}
    source_weights = weights.get("source_weights") if isinstance(weights.get("source_weights"), dict) else {}
    strategy_weights = weights.get("strategy_weights") if isinstance(weights.get("strategy_weights"), dict) else {}
    allowed = STRATEGY_TOPICS.get(strategy, STRATEGY_TOPICS["tech"])

    score = 10.0
    topic_allowed = topic in allowed
    if topic_allowed:
        score += 30.0
    else:
        score -= 55.0

    score *= float(strategy_weights.get(strategy) or 1.0)
    score *= float(topic_weights.get(topic) or 1.0)
    score *= float(cluster_weights.get(story_cluster(item)) or 1.0)
    score *= float(source_weights.get(source_key(item)) or 1.0)

    views = _as_int(item.get("view_count") or item.get("tiktok_video_views") or item.get("views"))
    comments = _as_int(item.get("comment_count") or item.get("comments"))
    if views:
        view_bonus = min(35.0, math.log10(views + 1) * 5.0)
        score += view_bonus if topic_allowed else view_bonus * 0.2
    if comments:
        comment_bonus = min(10.0, math.log10(comments + 1) * 2.0)
        score += comment_bonus if topic_allowed else comment_bonus * 0.2

    text = " ".join(str(item.get(k) or "") for k in ("title", "summary", "source", "channel")).lower()
    if strategy in {"tech", "tech_judgement", "business_finance"} and any(term.lower() in text for term in OFFBRAND_TERMS):
        score -= 28.0

    source_type = str(item.get("source_type") or "").lower()
    if source_type.startswith(("youtube", "tiktok", "google_trends")):
        score += 8.0
    elif source_type in {"last30days", "reddit", "hackernews"}:
        score += 5.0

    score += virality_score(item)

    if item.get("url"):
        score += 1.0
    return round(score, 3)


def candidate_threshold(strategy: str, weights: dict[str, Any] | None = None) -> float:
    weights = weights or load_weights()
    action = str(lane_action(strategy, weights).get("action") or "").lower()
    base = MIN_CANDIDATE_SCORE.get((strategy or "").lower(), 45.0)
    if action == "boost":
        return base + 4.0
    if action == "experiment":
        return base + 2.0
    return base


def passes_candidate_gate(item: dict[str, Any], strategy: str, weights: dict[str, Any] | None = None) -> bool:
    weights = weights or load_weights()
    score = float(item.get("media_ops_score") if item.get("media_ops_score") is not None else candidate_score(item, strategy, weights))
    return score >= candidate_threshold(strategy, weights)


def filter_candidates(
    items: list[dict[str, Any]],
    strategy: str,
    weights: dict[str, Any] | None = None,
    *,
    skip_clusters: set[str] | None = None,
) -> list[dict[str, Any]]:
    weights = weights or load_weights()
    ranked = rank_candidates(items, strategy, weights)
    skip_clusters = skip_clusters or set()
    return [
        item
        for item in ranked
        if passes_candidate_gate(item, strategy, weights)
        and str(item.get("media_ops_cluster") or "") not in skip_clusters
    ]


def select_diverse_candidates(
    items: list[dict[str, Any]],
    strategy: str,
    n: int,
    weights: dict[str, Any] | None = None,
    *,
    skip_clusters: set[str] | None = None,
    max_per_source: int = 1,
    max_per_cluster: int = 2,
) -> list[dict[str, Any]]:
    """Pick high-scoring candidates without making one video feel repetitive."""
    pool = filter_candidates(items, strategy, weights, skip_clusters=skip_clusters)
    selected: list[dict[str, Any]] = []
    source_counts: dict[str, int] = {}
    cluster_counts: dict[str, int] = {}

    def _try_add(item: dict[str, Any], *, enforce_source: bool, enforce_cluster: bool) -> bool:
        src = source_key(item)
        cluster = str(item.get("media_ops_cluster") or "")
        if enforce_source and source_counts.get(src, 0) >= max_per_source:
            return False
        if enforce_cluster and cluster_counts.get(cluster, 0) >= max_per_cluster:
            return False
        selected.append(item)
        source_counts[src] = source_counts.get(src, 0) + 1
        cluster_counts[cluster] = cluster_counts.get(cluster, 0) + 1
        return True

    for enforce_source, enforce_cluster in ((True, True), (False, True)):
        for item in pool:
            if len(selected) >= n:
                return selected
            if item in selected:
                continue
            _try_add(item, enforce_source=enforce_source, enforce_cluster=enforce_cluster)
    return selected


def rank_candidates(items: list[dict[str, Any]], strategy: str, weights: dict[str, Any] | None = None) -> list[dict[str, Any]]:
    weights = weights or load_weights()
    ranked = []
    for idx, item in enumerate(items):
        enriched = dict(item)
        enriched["media_ops_topic"] = classify_candidate(item)
        enriched["media_ops_cluster"] = story_cluster(item)
        enriched["media_ops_source_key"] = source_key(item)
        enriched["media_ops_virality_score"] = virality_score(item)
        enriched["media_ops_score"] = candidate_score(item, strategy, weights)
        enriched["_media_ops_original_index"] = idx
        ranked.append(enriched)
    ranked.sort(key=lambda x: (x.get("media_ops_score") or 0, -x.get("_media_ops_original_index", 0)), reverse=True)
    for item in ranked:
        item.pop("_media_ops_original_index", None)
    return ranked


def _as_int(value: Any) -> int:
    try:
        return int(float(value or 0))
    except (TypeError, ValueError):
        return 0


def _date_ordinal(value: str | date | None) -> int:
    if isinstance(value, date):
        return value.toordinal()
    if isinstance(value, str) and value:
        try:
            return datetime.fromisoformat(value[:10]).date().toordinal()
        except ValueError:
            pass
    return date.today().toordinal()
